{
 "title": "DACHS TSM Dashboard",
 "tags": [ "DACHS" ],
 "time": { "from": "2020-06-28T20:39:01.728Z", "to": "2020-07-03T03:17:49.695Z" },
 "templating": {
  "list": [
   {
    "name": "LG",
    "query": "CUR_TSM_ReadingValues\n| extend LG2=strcat(split(LG,\"/\")[0],\"-\",split(LG,\"/\")[1])\n| distinct LG2"
   }
  ]
 },
 "panels": [
  {
   "title": "Adresse",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "database": "dachsadxdb",
     "query": "CUR_TSM_ReadingValues\n| filter LG == strcat(split(\"$LG\",\"-\")[0],\"/\",split(\"$LG\",\"-\")[1])\n| summarize adresse=max(strcat(Ort,\", \",Strasse))\n"
    }
   ]
  },
  {
   "title": "Schema (Draw.io generiert)",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "database": "dachsadxdb",
     "query": "CUR_TSM_ReadingValues\n| filter Messgroesse != \"room_sensor_temperature\"\n| project timestamp,position=messpos_aus_freitext, datapoint=Messgroesse , value=Messwert\n| project timestamp, position, value"
    }
   ]
  },
  {
   "title": "Schema (Draw.io gezeichnet)",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 13, "w": 22, "x": 0, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "database": "dachsadxdb",
     "query": "CUR_TSM_ReadingValues\n| project timestamp,position=messpos_aus_freitext, datapoint=Messgroesse , value=Messwert\n| project timestamp, devID=strcat(position,\" \",datapoint), position, value"
    }
   ]
  },
  {
   "title": "Schema (Image geladen)",
   "type": "pierosavi-imageit-panel",
   "gridPos": { "h": 12, "w": 22, "x": 0, "y": 26 },
   "targets": [
    {
     "database": "dachsadxdb",
     "query": "CUR_TSM_ReadingValues\n| project timestamp,position=messpos_aus_freitext, datapoint=Messgroesse , value=Messwert\n| project timestamp, devID=strcat(position,\" \",datapoint), position, value"
    }
   ]
  },
  {
   "title": "Messwerte",
   "type": "graph",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "dachsadxdb",
     "query": "CUR_TSM_ReadingValues\n| summarize value=avg(Messwert) by strcat(messpos_aus_freitext,\"-\",Messgroesse), timestamp //bin(timestamp,15min)\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 49 },
   "targets": [
    {
     "alias": "ATS01",
     "database": "dachsadxdb",
     "query": "CUR_TSM_ReadingValues\n| filter $__timeFilter(timestamp)\n| project timestamp,position=messpos_aus_freitext, datapoint=Messgroesse , value=Messwert\n| project timestamp, devID=strcat(position,\" \",datapoint), position, value\n| summarize arg_max(timestamp,*) by devID\n"
    }
   ]
  }
 ]
}